"""Initial migration

Revision ID: 0e7f9f188cb6
Revises: 
Create Date: 2025-02-18 01:41:16.276826

"""
from typing import Sequence, Union

from alembic import op
from sqlmodel import sql
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e7f9f188cb6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_name'), 'action', ['name'], unique=False)
    op.create_table('allergen',
    sa.Column('id', sql.sqltypes.AutoString(), nullable=False),
    sa.Column('abbreviation', sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allergen_name'), 'allergen', ['name'], unique=False)
    op.create_table('claim',
    sa.Column('id', sql.sqltypes.AutoString(), nullable=False),
    sa.Column('abbreviation', sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sa.Enum('nutrient_related', 'dietary_form', name='claimtype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_name'), 'claim', ['name'], unique=False)
    op.create_table('recipe',
    sa.Column('title', sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_id', sql.sqltypes.AutoString(), nullable=False),
    sa.Column('format_version', sa.JSON(), nullable=False),
    sa.Column('recipe_metadata', sa.JSON(), nullable=False),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('instructions', sa.JSON(), nullable=False),
    sa.Column('nutrition', sa.JSON(), nullable=False),
    sa.Column('serving_info', sa.JSON(), nullable=False),
    sa.Column('visual_references', sa.JSON(), nullable=True),
    sa.Column('validation', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('file_path', sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool',
    sa.Column('id', sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comment', sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit',
    sa.Column('id', sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('weight', 'volume', 'length', 'time', 'temperature', 'count', 'energy', name='unittype'), nullable=False),
    sa.Column('conversion_factor', sa.Float(), nullable=True),
    sa.Column('conversion_formula', sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('email', sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('password_hash', sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('unit')
    op.drop_table('tool')
    op.drop_table('recipe')
    op.drop_index(op.f('ix_claim_name'), table_name='claim')
    op.drop_table('claim')
    op.drop_index(op.f('ix_allergen_name'), table_name='allergen')
    op.drop_table('allergen')
    op.drop_index(op.f('ix_action_name'), table_name='action')
    op.drop_table('action')
    # ### end Alembic commands ###
