"""added saves and relationship between users and recipes for the saves

Revision ID: 138a796027b5
Revises: 0e7f9f188cb6
Create Date: 2025-02-26 12:30:26.583114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '138a796027b5'
down_revision: Union[str, None] = '0e7f9f188cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('save_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'save_count')
    # ### end Alembic commands ###
